### ISSUE TITLE
[Feature Request] Magic comments for HTML

### ISSUE THREAD

**Issue by JonasWischeropp** [ltex-plus/ltex-ls-plus#31]
Foremost, thank you for your work on this project.

I was wondering if there is a specific problem that prevents the parsing of magic comments in (X)HTML files,
because markdown is supported with HTML style comments.
Shouldn't it be possible to use the same `RegexCodeFragmentizer` that is used in [`MarkdownFragmentizer`](https://github.com/ltex-plus/ltex-ls-plus/blob/c38134959964b03a4b9c0d61edb18937ef6efe84/src/main/kotlin/org/bsplines/ltexls/parsing/markdown/MarkdownFragmentizer.kt#L16) to implement the [`HtmlFragmentizer`](https://github.com/ltex-plus/ltex-ls-plus/blob/c38134959964b03a4b9c0d61edb18937ef6efe84/src/main/kotlin/org/bsplines/ltexls/parsing/html/HtmlFragmentizer.kt#L14)?

If there is no known reason this shouldn't work, and you want me to, I could look into it and create a PR.

This feature would be nice to have, to for example set the language per HTML document.

**Comment by spitzerd** [comment]
I would be thankful if you could submit a PR. Any help is appreciated. You are right, magic comments for (X)HTML are currently not supported. Because I "inherited" this project, I don't know the reason why.
