### ISSUE TITLE
Add option to strip comments from LaTeX

### ISSUE THREAD

**Issue by rpls** [ltex-plus/ltex-ls-plus#51]
**Is your feature request related to a problem? Please describe.**
Since the Paid version of LanguageTool is quite limited in terms of request size, additional options to save on request size would be nice (the implemented fixes in 18.2.0 already help a lot, but one could always do more). From what I gather, comments are sent as markup and thus not really checked, but still count towards the size limit per request. The API documentation isn't really all that clear, whether the limit is "characters to be checked" (suggested by https://languagetool.org/http-api/swagger-ui/) or "byte size of the request" (suggested by https://dev.languagetool.org/public-http-api)?

**Describe the solution you'd like**
I'm not sure if it's possible to just skip the comments, e.g., if the markup is used to do the mapping from LT response to original source file? But since they are not really spellchecked by LT, it might be worth it to have a method of not submitting them in the request to save on request size.

**Describe alternatives you've considered**
Not really that well versed in the LanguageTool API or LTeX source to make alternative suggestions here.

**Additional context**
Since LaTeX documents can get quite large, reducing request size is a worthwhile effort. While one can just split larger documents into multiple source files (good idea in most cases anyway), it's still quite possible to hit rate limits in terms of req/min.

**Comment by real-or-random** [comment]
I'm the author of the changes in 18.0.2

> The API documentation isn't really all that clear, whether the limit is "characters to be checked" (suggested by [languagetool.org/http-api/swagger-ui](https://languagetool.org/http-api/swagger-ui/)) or "byte size of the request" (suggested by [dev.languagetool.org/public-http-api](https://dev.languagetool.org/public-http-api))?

IIRC, it was the latter when I tried it.

> I'm not sure if it's possible to just skip the comments, e.g., if the markup is used to do the mapping from LT response to original source file

It is. Of course, this can be fixed, but I don't think it's worth the hassle. There's only so much you can gain for typical documents. Maybe an option to skip all "markup" is better (at least the one without `interpretAs`, or even better, do the `interpretAs` locally).

The thing is that this does not really resolve the underlying issue. The only thing that does is to split larger documents. And this is hard because one needs to keep track of requests per minute etc. 



By the way, please join me in complaining about the limits... Their response was really not great. https://forum.languagetool.org/t/disappointing-api-limits-for-premium/8728

**Comment by spitzerd** [comment]
@real-or-random I fully agree with you and thank you for your contribution.

Another option to split a file into smaller chunks of text is to use the [magic command](https://ltex-plus.github.io/ltex-plus/advanced-usage.html). But the more chunks you have, the more requests you have. So you have to keep the amount of requests small without running into an HTTP 413.
Here is an example for LaTeX:
```
Text 1
% LTeX:
Text 2
```
The example above will result in two 2 requests for LanguageTool.

If you have many lines of comments, you can disable LTeX for this part.
Here is an example for LaTeX:
```
Text to be spell checked
% LTeX: enabled=false
% Comment which is not sent to LanguageTool
Text which is not sent to LanguageTool
% LTeX: enabled=true
Text to be spell checked
```

**Comment by lamBOOO** [comment]
I tried the splitting approach with "% LTeX:" comments for a while. But the response times were still very high (~10 secs), so I switched to the local installation of LT again 😅
