### ISSUE TITLE
Add ltex-ls-plus to mason registry for neovim

### ISSUE THREAD

**Issue by Holmgren825** [ltex-plus/ltex-ls-plus#53]
Installation instructions for neovim are, as far as I understand them, not applicable or outdated.
Ltex-ls is easily available for neovim users through the mason registry, https://github.com/mason-org/mason-registry. Would it be in scope to add this repo to mason as well? I figure it would be a pretty easy addition.

**Comment by misaflo** [comment]
Someone did a [pull request](https://github.com/mason-org/mason-registry/pull/7974).

**Comment by Holmgren825** [comment]
Nice, we'll have to wait for that one I guess!

**Comment by spitzerd** [comment]
@misaflo Thank you for the hint. I was already working on a pull request for the mason registry.

**Comment by foxyseta** [comment]
> Someone did a [pull request](https://github.com/mason-org/mason-registry/pull/7974).

It was me! In case it does not get merged, I am also considering setting up [my own Mason registry](https://github.com/visimp/visimp/issues/124).
