### ISSUE TITLE
Feature Request: Reduce RAM use

### ISSUE THREAD

**Issue by David-Else** [ltex-plus/ltex-ls-plus#54]
I tried the latest `18.3.0` version using the built in Java runtime and it still uses a huge amount of RAM, is there anything that can be done? The following image shows just checking a 690 line markdown file and 1.2 GB is used.

![image](https://github.com/user-attachments/assets/6cc21aad-c97f-459a-847d-80719d152a51)

[languagetool-rust](https://github.com/jeertmans/languagetool-rust) seems abandoned, but reading the pull requests it seems it might be coming back to life soon.

I am using the Helix editor.

Thanks for bringing this great language server back to life!

**Comment by spitzerd** [comment]
The RAM usage is not a LTeX+ issue but a LanguageTool issue.
I just made test using the plain LanguageTool.
1. Download the LanguageTool Desktop version for offline use: https://dev.languagetool.org/http-server#getting-the-server
![Screenshot 2024-12-05 194014](https://github.com/user-attachments/assets/0fa34454-a46f-4481-a9d1-991171f7fe05)
3. Extract the ZIP file and run languagetool.jar
4. Check the RAM usage. I entered approx. 680 words and LanguageTool uses 1.7 GB. Sure, the GUI requires some RAM as well. I also tried the server and command line programs and the amount of RAM is almost the same.
<img width="1041" alt="Untitled" src="https://github.com/user-attachments/assets/e435104e-75a7-4047-a065-740ee0b82098">

The reason why [languagetool-rust](https://github.com/jeertmans/languagetool-rust) uses less RAM is, that it does not have an included LanguageTool server. By default it uses the public API of https://languagetool.org. If you want to run [languagetool-rust](https://github.com/jeertmans/languagetool-rust) offline/locally, you need a standalone LanguageTool server.



If you have too less RAM on your computer, you can run LanguageTool on your own server and use the setting [ltex.languageToolHttpServerUri](https://ltex-plus.github.io/ltex-plus/settings.html#ltexlanguagetoolhttpserveruri).
Alternatively, you can use the public API of https://languagetool.org
